version: "3.9"

services:
  # Robot container (headless, no GUI tools)
  nera_robot:
    build:
      context: .
      target: robot
    image: nera_bot:robot
    network_mode: host
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0   # example: motor controller
      - /dev/video0:/dev/video0     # example: camera
    volumes:
      - ./src:/ros2_ws/src:rw
    command: >
      bash -c "ros2 launch nera_bot bringup.launch.py"

  # Dev container (RViz, Gazebo, debugging)
  nera_dev:
    build:
      context: .
      target: dev
    image: nera_bot:dev
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./src:/ros2_ws/src:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/dri:/dev/dri   # GPU passthrough for rendering
    command: >
      bash -c "ros2 launch nera_bot sim.launch.py"
